### ISSUE TITLE
update config for crackclient.py to pull from $HOME instead of config/

### ISSUE THREAD

**Issue by NetworkJack2** [averagesecurityguy/crack#5]
please change

``config_file = "config/crackclient.cfg"
``

to
``config_file = os.getenv("HOME") +"/.config/crackclient.cfg"``

This way it can run without root

**Comment by averagesecurityguy** [comment]
How are you installing and running the program? There shouldn't be a requirement to run as root.

**Comment by NetworkJack2** [comment]
From an Archlinux package

**Comment by averagesecurityguy** [comment]
Can you use the -c flag to provide a config file?

**Comment by NetworkJack2** [comment]
realistically: no

I am suggesting "sane defaults" for a system where this is installed as a system package.
